version: '3.8'

services:
    ollama:
        image: ollama/ollama:latest
        container_name: ollama
#        ports:
#            - "11434:11434"
        volumes:
            - ./ollama_data:/root/.ollama
        networks:
            - app_network

    mcp:
        image: node:20-alpine
        container_name: mcp
        working_dir: /app
        volumes:
            - ./mcp:/app
        ports:
            - "3000:3000"
        command: sh -c "npm install"
        depends_on:
            - ollama
            - chromadb
        networks:
            - app_network
        environment:
            - NODE_ENV=development

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        volumes:
            - ./php:/var/www/html
            - .lo/../:/var/www/project
#        ports:
#            - "9000:9000"
#            - "9003:9003"
        environment:
            - PHP_IDE_CONFIG=serverName=Docker
        depends_on:
            - ollama
            - chromadb
        networks:
            - app_network

    chromadb:
        image: chromadb/chroma:latest
        container_name: chromadb
        ports:
            - "8000:8000"
        environment:
            - CHROMADB_PORT=8000
        volumes:
            - ./chromadb_data:/data
        networks:
            - app_network

networks:
    app_network:
        driver: bridge

volumes:
    ollama_data:
    chromadb_data:
